---
/boreas/online_fgo:
    ros__parameters:
      GNSSFGO:
        IntegratorBase:
          StateSensorSyncTimeThreshold: 0.03
          IMUSensorSyncTimeThreshold: 0.02

        BoreasLCIntegrator:
          integratorPlugin: "GNSSLCIntegrator"
          odomPVATopic: "/boreas/gps_raw"
          useForInitialization: true
          useHeaderTimestamp: true
          GNSSMeasurementFrequency: 200
          PVTSource: "boreas"
          hasHeading: true
          hasPitch: true
          hasRoll: true
          integrateAttitude: false
          integrateVelocity: false
          onlyRTKFixed: false

          zeroVelocityThreshold: 0.05
          varScaleRTKFloat: 1.
          varScaleSingle:   1.
          varScaleHeadingSingle: 5.
          varScaleHeadingRTKFloat: 3.
          varScaleNoSolution: 1000.

          solutionSyncQueueSize: 10
          MsgSyncLowerBound: 50000000

          fixedVelVar: 0.5
          posVarScale: 20.
          velVarScale: 5.
          headingVarScale: 1.
          headingOffsetDeg: 0.

          attitudeFrame: "enu"
          attitudeType: "3d"
          velocityFrame: "enu"
          velocityType: "3d"
          noiseModelAttitude: "cauchy"
          noiseModelVelocity: "cauchy"
          noiseModelPosition: "cauchy"
          robustParamPos: 0.5
          robustParamVel: 0.5
          robustParamAtt: 0.5

        LIOIntegrator:
          notIntegrating: false
          integratorPlugin: "LIOIntegrator"
          pointCloudTopic: "/boreas/velodyne_points"
          lidarFrame: "velodyne"
          baselinkFrame: "base_link"
          odometryFrame: "odom"
          mapFrame: "map"
          savePCD: false
          savePCDDirectory: ""

          integrateBetweenPose: true
          integrateGlobalPose: false
          odomPoseVar: [0.5, 0.5, 0.5, 1., 1., 1.]
          noiseModelOdomPose: "Cauchy"
          robustParamOdomPose: 0.5

          N_SCAN: 128
          Horizon_SCAN: 1800
          downsampleRate: 10
          lidarMinRange: 3.
          lidarMaxRange: 1000.
          maxPosePriorLiDARMsgAging: 0.1
          edgeFeatureMinValidNum: 10
          surfFeatureMinValidNum: 100
          numberOfCores: 16
          mappingProcessInterval: 0.15
          varianceRoll: 0.01
          variancePitch: 0.01
          varianceYaw: 0.01
          varianceX: 0.01
          varianceY: 0.01
          varianceZ: 0.01

          surroundingKeyframeSearchRadius: 50.
          loopClosureEnableFlag: true
          loopClosureFrequency: 1.
          surroundingKeyframeSize: 50
          historyKeyframeSearchRadius: 15.
          historyKeyframeSearchTimeDiff: 30.
          historyKeyframeSearchNum: 30
          historyKeyframeFitnessScore: 0.3
          globalMapVisualizationSearchRadius: 1000.
          globalMapVisualizationPoseDensity: 10.
          globalMapVisualizationLeafSize: 1.
          imuRPYWeight: 0.01
          z_tollerance: 1000.
          rotation_tollerance: 1000.
          mappingCornerLeafSize: 0.2
          mappingSurfLeafSize: 0.4
          surroundingkeyframeAddingDistThreshold: 0.2
          surroundingkeyframeAddingAngleThreshold: 0.2
          surroundingKeyframeDensity: 2.0

          maxNumCachedMap: 1000000
          maxPointAge: 10.
          scan2MapOptIteration: 30
          minSizeCurrentKeyframeCloud: 300
          minSizePreviousKeyframeCloud: 1000
          icpMaxIterations: 100
          icpTransformEpsilon: 1e-6
          icpEuclideanFitnessEpsilon: 1e-6
          icpRANSACIterations: 0
          freqLoopDetectionInSec: 5
          freqVisualizationInSec: 5




















