---
/deutschland/online_fgo:
    ros__parameters:
      use_sim_time: true
      GNSSFGO:
        verbose: false
        useIMUAsTimeReference: true
        bufferSize: 10
        optFrequency: 5 #in Hz
        calcErrorOnOpt: true
        cleanIMUonInit: true    # set this flag to clean the imu data before the timestamp of the initializing state
        useHeaderTimestamp: true

        Initialization:
          initSigmaX: [ 1., 1., 1., 0.1, 0.1, 0.1 ] #first 3 for Rot in degree, other for translation in m
          initSigmaV: [ 1., 1., 1. ]
          initSigmaW: [ 0.05, 0.05, 0.05]
          initSigmaB: [ 0.5, 0.5, 0.5, 0.05, 0.05, 0.05] #first for b_a, second for b_g in degree
          initSigmaC: [ 1000., 10. ] #cb in m, cd in m/s

        IMUPreintegrator:
          accelerometerSigma: 8e-4 #3.9939570888238808e-04 #8e-4 # 8e-4
          integrationSigma: 1e-5  #1e-5
          gyroscopeSigma: 0.0006939335887264338 #1.5636343949698187e-05   #52e-4 # 52e-5
          biasAccSigma: 0.000167 # 4e-4
          biasOmegaSigma: 2.91e-6  #87e-5 # 87e-5
          biasAccOmegaInt: 0.00001 # 0.00001

        Graph:
          publishResiduals: false
          IMUMeasurementFrequency: 200  #
          useGPPriorFactor: true
          gpType: 'WNOJ'  # 'WNOA'
          useGPInterpolatedFactor: true
          useEstimatedVarianceAfterInit: false

          AutoDiffNormalFactor: true
          AutoDiffGPInterpolatedFactor: true
          AutoDiffGPMotionPriorFactor: false
          GPInterpolatedFactorCalcJacobian: true

          StateMeasSyncUpperBound: 0.02
          StateMeasSyncLowerBound: -0.02
          useMMFactor: false
          useConstDriftFactor: false

          noiseModelClockFactor: "huber"
          robustParamClockFactor: 10.
          constDriftStd: 0.5
          constBiasStd: .1
          motionModelStd: 1.
          angularRateStd: 0.01
          magnetometerStd: 0.01

          NoOptimizationWhileNoMeasurement: false
          NoOptimizationNearZeroVelocity: true
          VoteNearZeroVelocity: 0.1 # 20%
          NoOptimizationAfterStates: 0

        VehicleParameters:
          # Parrameters DELoco
          transIMUToReference: [ 0.3665, -0.628, -0.2383 ] # [0.0, 0.0, 0.0]
          rotIMUToReference: [1., 0., 0., 0., 1., 0., 0., 0., 1.]
          transIMUToGNSSAnt1: [ 0.3665, -0.628, -0.2383 ] # [0.0, 0.0, 0.0]
          transIMUToGNSSAnt2: [ 0.3665, 0.619, -0.2383 ] # [0.0, 0.0, 0.0]
          transIMUToLiDAR: [0.301411, 0., -.0596]
          rotIMUToLiDAR: [1., 0., 0., 0., -1., 0., 0., 0., -1. ]
          transIMUToCorrevit: [ -1.78, 0., 1.2 ]

        Integrators: [ "IRTPVALCIntegrator", "UbloxLCIntegrator", "CorrevitIntegrator"]   # ["UbloxLCIntegrator", "CorrevitIntegrator", "GNSSTCIntegrator", "LIOIntegrator"]

        Optimizer:
          #undefined, BatchFixedLag, IncrementalFixedLag
          smootherType: 'IncrementalFixedLag'
          smootherLag: 3. #marginalization threshhold
          #QcGPWNOJInterpolatorFull: [ 10000., 10000., 10000., 10000., 10000., 10000. ]
          #QcGPWNOJMotionPriorFull: [ 10000., 10000., 10000., 10000., 10000., 10000. ]
          QcGPWNOJInterpolatorFull: [ 10000., 10000., 10000., 10000., 10000., 10000. ]
          QcGPWNOJMotionPriorFull: [ 10000., 10000., 10000., 10000., 10000., 10000. ]
          #QcGPWNOAInterpolator: 0.5
          #QcGPWNOAMotionPrior: 0.5
          QcGPWNOAInterpolatorFull: [ 1.666669, 1.666669, 1.666669, 1.666669, 1.666669, 1.666669 ]
          QcGPWNOAMotionPriorFull: [ 1.666669, 1.666669, 1.666669, 1.666669, 1.666669, 1.666669 ]
          #QcGPWNOAInterpolatorFull: [ .16691, .16691, .16691, 1.666669, 1.666669, 1.666669 ]
          #QcGPWNOAMotionPriorFull: [ .16691, .16691, .16691, 1.666669, 1.666669, 1.666669 ]
          #QcGPWNOAInterpolatorFull: [ 0.5, 0.5, 0.5, 0.5, 0.5, 0.5 ]
          #QcGPWNOAMotionPriorFull: [ 0.5, 0.5, 0.5, 0.5, 0.5, 0.5 ]
